// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    //This assumes you have a .env file with a DATABASE_URL variable,
    // and that it is a valid connection string for your database.
    url: process.env["DATABASE_URL"]!,
  },
});
